USE [master]
GO
/****** Object:  Database [Item Specifications]    Script Date: 11/24/2024 7:55:49 PM ******/
CREATE DATABASE [Item Specifications]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Item Specifications', FILENAME = N'C:\Users\chumm\OneDrive\Documents\School Work\ACT\CS412 [C#]\Semester Project\DB\Item Specifications.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Item Specifications_log', FILENAME = N'C:\Users\chumm\OneDrive\Documents\School Work\ACT\CS412 [C#]\Semester Project\DB\Item Specifications_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Item Specifications] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Item Specifications].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Item Specifications] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Item Specifications] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Item Specifications] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Item Specifications] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Item Specifications] SET ARITHABORT OFF 
GO
ALTER DATABASE [Item Specifications] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Item Specifications] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Item Specifications] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Item Specifications] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Item Specifications] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Item Specifications] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Item Specifications] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Item Specifications] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Item Specifications] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Item Specifications] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Item Specifications] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Item Specifications] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Item Specifications] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Item Specifications] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Item Specifications] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Item Specifications] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Item Specifications] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Item Specifications] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Item Specifications] SET  MULTI_USER 
GO
ALTER DATABASE [Item Specifications] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Item Specifications] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Item Specifications] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Item Specifications] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Item Specifications] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Item Specifications] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Item Specifications] SET QUERY_STORE = OFF
GO
USE [Item Specifications]
GO
/****** Object:  Table [dbo].[BANK]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTRY_CID] [int] NOT NULL,
 CONSTRAINT [PK_BANK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANK_ACCOUNT]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANK_ACCOUNT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [int] NOT NULL,
	[IBAN] [nvarchar](34) NOT NULL,
	[BANK_ID] [int] NOT NULL,
 CONSTRAINT [PK_BANK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CITY]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REGION_ID] [int] NOT NULL,
	[SHIPMENT_COMPANY_CID] [int] NOT NULL,
	[URBAN_AREA_TYPE_CID] [int] NOT NULL,
 CONSTRAINT [PK_CITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COUNTRY]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COUNTRY](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_CATEGORY_CID] [int] NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER_CATEGORY]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER_CATEGORY](
	[CID] [int] NOT NULL,
	[LEVEL] [int] NOT NULL,
	[PARENT_CATEGORY_CID] [int] NULL,
 CONSTRAINT [PK_CUSTOMER_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER_PLACE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER_PLACE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[ADDRESS] [nvarchar](64) NOT NULL,
	[CITY_ID] [int] NOT NULL,
 CONSTRAINT [PK_CUSTOMER_PLACE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IS_CUSTOMER_INVOICE] [int] NOT NULL,
	[CUSTOMER_ID] [int] NULL,
	[SUPPLIER_ID] [int] NULL,
	[ITEM_ORDER_ID] [int] NOT NULL,
 CONSTRAINT [PK_INVOICE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICE_LINE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE_LINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_ID] [int] NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[QTY] [float] NOT NULL,
	[PRICE] [float] NOT NULL,
	[LINE_TOTAL] [float] NOT NULL,
 CONSTRAINT [PK_INVOICE_LINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](32) NOT NULL,
	[MEASUREMENT_UNIT_CID] [int] NOT NULL,
	[ITEM_CATEGORY_CID] [int] NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[PRICE] [decimal](18, 2) NULL,
	[ISCOMPANYPRODUCED] [bit] NULL,
	[QUANTITY] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_CATEGORY]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_CATEGORY](
	[CID] [int] NOT NULL,
	[LEVEL] [int] NOT NULL,
	[PARENT_CATEGORY_CID] [int] NULL,
	[CATEGORY_NAME] [nvarchar](100) NULL,
 CONSTRAINT [PK_ITEM_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_INV]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_INV](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STORE_CID] [int] NOT NULL,
 CONSTRAINT [FK_ITEM_INV] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_INV_LINE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_INV_LINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_PKG_ID] [int] NOT NULL,
	[STORE_POS_CID] [int] NOT NULL,
	[STORED_QTY] [float] NOT NULL,
 CONSTRAINT [PK_ITEM_INV_LINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_ORDER]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_ORDER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IS_CUSTOMER_ORDER] [int] NOT NULL,
	[CUSTOMER_ID] [int] NULL,
	[SUPPLIER_ID] [int] NULL,
	[ORDER_DATETIME] [datetime] NOT NULL,
	[STORE_CID] [int] NOT NULL,
 CONSTRAINT [PK_ITEM_ORDER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_ORDER_LINE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_ORDER_LINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_ORDER_ID] [int] NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[QTY] [float] NOT NULL,
 CONSTRAINT [PK_ITEM_ORDER_LINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_PICKING]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_PICKING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_ORDER_ID] [int] NOT NULL,
	[PICKING_START_DATETIME] [datetime] NOT NULL,
	[PICKING_END_DATETIME] [datetime] NOT NULL,
	[STORE_CID] [int] NOT NULL,
 CONSTRAINT [PK_ITEM_PICKING] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_PICKING_LINE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_PICKING_LINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_PICKING_ID] [int] NOT NULL,
	[ITEM_ORDER_LINE_ID] [int] NOT NULL,
	[ITEM_PKG_ID] [int] NOT NULL,
	[STORE_POS_CID] [int] NULL,
	[PICKED_PACKAGES] [int] NOT NULL,
	[ORDERED_QTY_IN_UNIT] [float] NOT NULL,
 CONSTRAINT [PK_ITEM_PICKING_LINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_PKG]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_PKG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[BARCODE] [nvarchar](32) NOT NULL,
	[SERIAL_NUM] [bigint] NOT NULL,
	[PACKAGE_TYPE_CID] [int] NOT NULL,
 CONSTRAINT [PK_ITEM_PKG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITEM_SPEC]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_SPEC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[SPEC_TYPE_CID] [int] NULL,
	[TITLE] [nvarchar](255) NOT NULL,
	[VALUE] [int] NOT NULL,
 CONSTRAINT [PK_ITEM_SPEC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEASUREMENT_UNIT]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEASUREMENT_UNIT](
	[CID] [int] NOT NULL,
	[UNIT_NAME] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_MEASUREMENT_UNIT] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PACKAGE_TYPE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PACKAGE_TYPE](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_PACKAGE_TYPE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IS_CUSTOMER_PAYMENT] [int] NOT NULL,
	[CUSTOMER_ID] [int] NULL,
	[SUPPLIER_ID] [int] NULL,
	[ITEM_ORDER_ID] [int] NOT NULL,
	[PAYMENT_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_PAYMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT_LINE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT_LINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAYMENT_ID] [int] NOT NULL,
	[PAYMENT_TYPE_CID] [int] NOT NULL,
	[AMOUNT] [float] NOT NULL,
	[BANK_ACCOUNT_ID] [int] NULL,
 CONSTRAINT [PK_PAYMENT_LINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT_TYPE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT_TYPE](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_PAYMENT_TYPE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTION]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTION_PHASE_CID] [int] NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[QTY] [float] NOT NULL,
 CONSTRAINT [PK_PRODUCTION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTION_MACHINE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTION_MACHINE](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTION_MACHINE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTION_PART]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTION_PART](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTION_ID] [int] NOT NULL,
	[NUM] [int] NOT NULL,
	[ITEM_ID] [int] NOT NULL,
	[PRODUCTION_MACHINE_CID] [int] NOT NULL,
 CONSTRAINT [FK_PRODUCTION_PART] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTION_PHASE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTION_PHASE](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTION_PHASE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGION]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](32) NOT NULL,
	[COUNTRY_CID] [int] NOT NULL,
 CONSTRAINT [PK_REGION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SHIPMENT_COMPANY]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SHIPMENT_COMPANY](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_SHIPMENT_COMPANY] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SPEC_TYPE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SPEC_TYPE](
	[CID] [int] NOT NULL,
	[SPECIFICATION_NAME] [nvarchar](255) NULL,
	[UNIT_NAME] [nvarchar](100) NULL,
 CONSTRAINT [PK_SPEC_TYPE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STORE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STORE](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_STORE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STORE_POS]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STORE_POS](
	[CID] [int] NOT NULL,
	[STORE_CID] [int] NOT NULL,
 CONSTRAINT [PK_STORE_POS] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_CATEGORY_CID] [int] NOT NULL,
 CONSTRAINT [PK_SUPPLIER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER_CATEGORY]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER_CATEGORY](
	[CID] [int] NOT NULL,
	[LEVEL] [int] NOT NULL,
	[PARENT_CATEGORY_CID] [int] NULL,
 CONSTRAINT [PK_SUPPLIER_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIER_PLACE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIER_PLACE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [int] NOT NULL,
	[ADDRESS] [nvarchar](64) NOT NULL,
	[CITY_ID] [int] NOT NULL,
 CONSTRAINT [PK_SUPPLIER_PLACE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[URBAN_AREA_TYPE]    Script Date: 11/24/2024 7:55:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[URBAN_AREA_TYPE](
	[CID] [int] NOT NULL,
 CONSTRAINT [PK_URBAN_AREA_TYPE] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMER_CATEGORY] ADD  DEFAULT ((0)) FOR [LEVEL]
GO
ALTER TABLE [dbo].[INVOICE] ADD  DEFAULT ((0)) FOR [IS_CUSTOMER_INVOICE]
GO
ALTER TABLE [dbo].[ITEM] ADD  DEFAULT ((0.0)) FOR [PRICE]
GO
ALTER TABLE [dbo].[ITEM] ADD  DEFAULT ((0)) FOR [ISCOMPANYPRODUCED]
GO
ALTER TABLE [dbo].[ITEM] ADD  DEFAULT ((0)) FOR [QUANTITY]
GO
ALTER TABLE [dbo].[ITEM_CATEGORY] ADD  DEFAULT ((0)) FOR [LEVEL]
GO
ALTER TABLE [dbo].[ITEM_ORDER] ADD  DEFAULT ((0)) FOR [IS_CUSTOMER_ORDER]
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE] ADD  DEFAULT ((0)) FOR [PICKED_PACKAGES]
GO
ALTER TABLE [dbo].[PAYMENT] ADD  DEFAULT ((0)) FOR [IS_CUSTOMER_PAYMENT]
GO
ALTER TABLE [dbo].[PAYMENT_LINE] ADD  DEFAULT ((0)) FOR [AMOUNT]
GO
ALTER TABLE [dbo].[PRODUCTION] ADD  DEFAULT ((0)) FOR [QTY]
GO
ALTER TABLE [dbo].[SUPPLIER_CATEGORY] ADD  DEFAULT ((0)) FOR [LEVEL]
GO
ALTER TABLE [dbo].[BANK]  WITH CHECK ADD  CONSTRAINT [FK_BANK_REF_COUNTRY] FOREIGN KEY([COUNTRY_CID])
REFERENCES [dbo].[COUNTRY] ([CID])
GO
ALTER TABLE [dbo].[BANK] CHECK CONSTRAINT [FK_BANK_REF_COUNTRY]
GO
ALTER TABLE [dbo].[BANK_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_BANK_ACCOUNT_REF_BANK] FOREIGN KEY([BANK_ID])
REFERENCES [dbo].[BANK] ([ID])
GO
ALTER TABLE [dbo].[BANK_ACCOUNT] CHECK CONSTRAINT [FK_BANK_ACCOUNT_REF_BANK]
GO
ALTER TABLE [dbo].[BANK_ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_BANK_ACCOUNT_REF_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[SUPPLIER] ([ID])
GO
ALTER TABLE [dbo].[BANK_ACCOUNT] CHECK CONSTRAINT [FK_BANK_ACCOUNT_REF_SUPPLIER]
GO
ALTER TABLE [dbo].[CITY]  WITH CHECK ADD  CONSTRAINT [FK_CITY_REF_REGION] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[REGION] ([ID])
GO
ALTER TABLE [dbo].[CITY] CHECK CONSTRAINT [FK_CITY_REF_REGION]
GO
ALTER TABLE [dbo].[CITY]  WITH CHECK ADD  CONSTRAINT [FK_CITY_REF_SHIPMENT_COMPANY] FOREIGN KEY([SHIPMENT_COMPANY_CID])
REFERENCES [dbo].[SHIPMENT_COMPANY] ([CID])
GO
ALTER TABLE [dbo].[CITY] CHECK CONSTRAINT [FK_CITY_REF_SHIPMENT_COMPANY]
GO
ALTER TABLE [dbo].[CITY]  WITH CHECK ADD  CONSTRAINT [FK_CITY_REF_URBAN_AREA_TYPE] FOREIGN KEY([URBAN_AREA_TYPE_CID])
REFERENCES [dbo].[URBAN_AREA_TYPE] ([CID])
GO
ALTER TABLE [dbo].[CITY] CHECK CONSTRAINT [FK_CITY_REF_URBAN_AREA_TYPE]
GO
ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_REF_CUSTOMER_CATEGORY] FOREIGN KEY([CUSTOMER_CATEGORY_CID])
REFERENCES [dbo].[CUSTOMER_CATEGORY] ([CID])
GO
ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_REF_CUSTOMER_CATEGORY]
GO
ALTER TABLE [dbo].[CUSTOMER_CATEGORY]  WITH CHECK ADD  CONSTRAINT [SK_CUSTOMER_CATEGORY_01] FOREIGN KEY([PARENT_CATEGORY_CID])
REFERENCES [dbo].[CUSTOMER_CATEGORY] ([CID])
GO
ALTER TABLE [dbo].[CUSTOMER_CATEGORY] CHECK CONSTRAINT [SK_CUSTOMER_CATEGORY_01]
GO
ALTER TABLE [dbo].[CUSTOMER_PLACE]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_PLACE_REF_CITY] FOREIGN KEY([CITY_ID])
REFERENCES [dbo].[CITY] ([ID])
GO
ALTER TABLE [dbo].[CUSTOMER_PLACE] CHECK CONSTRAINT [FK_CUSTOMER_PLACE_REF_CITY]
GO
ALTER TABLE [dbo].[CUSTOMER_PLACE]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_PLACE_REF_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO
ALTER TABLE [dbo].[CUSTOMER_PLACE] CHECK CONSTRAINT [FK_CUSTOMER_PLACE_REF_CUSTOMER]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_REF_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_INVOICE_REF_CUSTOMER]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_REF_ITEM_ORDER] FOREIGN KEY([ITEM_ORDER_ID])
REFERENCES [dbo].[ITEM_ORDER] ([ID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_INVOICE_REF_ITEM_ORDER]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_REF_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[SUPPLIER] ([ID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_INVOICE_REF_SUPPLIER]
GO
ALTER TABLE [dbo].[INVOICE_LINE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_LINE_REF_INVOICE] FOREIGN KEY([INVOICE_ID])
REFERENCES [dbo].[INVOICE] ([ID])
GO
ALTER TABLE [dbo].[INVOICE_LINE] CHECK CONSTRAINT [FK_INVOICE_LINE_REF_INVOICE]
GO
ALTER TABLE [dbo].[INVOICE_LINE]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_LINE_REF_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([ID])
GO
ALTER TABLE [dbo].[INVOICE_LINE] CHECK CONSTRAINT [FK_INVOICE_LINE_REF_ITEM]
GO
ALTER TABLE [dbo].[ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_REF_ITEM_CATEGORY] FOREIGN KEY([ITEM_CATEGORY_CID])
REFERENCES [dbo].[ITEM_CATEGORY] ([CID])
GO
ALTER TABLE [dbo].[ITEM] CHECK CONSTRAINT [FK_ITEM_REF_ITEM_CATEGORY]
GO
ALTER TABLE [dbo].[ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_REF_MEASUREMENT_UNIT] FOREIGN KEY([MEASUREMENT_UNIT_CID])
REFERENCES [dbo].[MEASUREMENT_UNIT] ([CID])
GO
ALTER TABLE [dbo].[ITEM] CHECK CONSTRAINT [FK_ITEM_REF_MEASUREMENT_UNIT]
GO
ALTER TABLE [dbo].[ITEM_CATEGORY]  WITH CHECK ADD  CONSTRAINT [SK_ITEM_CATEGORY_01] FOREIGN KEY([PARENT_CATEGORY_CID])
REFERENCES [dbo].[ITEM_CATEGORY] ([CID])
GO
ALTER TABLE [dbo].[ITEM_CATEGORY] CHECK CONSTRAINT [SK_ITEM_CATEGORY_01]
GO
ALTER TABLE [dbo].[ITEM_INV]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_INV_REF_STORE] FOREIGN KEY([STORE_CID])
REFERENCES [dbo].[STORE] ([CID])
GO
ALTER TABLE [dbo].[ITEM_INV] CHECK CONSTRAINT [FK_ITEM_INV_REF_STORE]
GO
ALTER TABLE [dbo].[ITEM_INV_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_INV_LINE_REF_STORE_POS] FOREIGN KEY([STORE_POS_CID])
REFERENCES [dbo].[STORE_POS] ([CID])
GO
ALTER TABLE [dbo].[ITEM_INV_LINE] CHECK CONSTRAINT [FK_ITEM_INV_LINE_REF_STORE_POS]
GO
ALTER TABLE [dbo].[ITEM_INV_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_INV_REF_ITEM_PKG] FOREIGN KEY([ITEM_PKG_ID])
REFERENCES [dbo].[ITEM_PKG] ([ID])
GO
ALTER TABLE [dbo].[ITEM_INV_LINE] CHECK CONSTRAINT [FK_ITEM_INV_REF_ITEM_PKG]
GO
ALTER TABLE [dbo].[ITEM_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_ORDER_REF_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO
ALTER TABLE [dbo].[ITEM_ORDER] CHECK CONSTRAINT [FK_ITEM_ORDER_REF_CUSTOMER]
GO
ALTER TABLE [dbo].[ITEM_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_ORDER_REF_STORE] FOREIGN KEY([STORE_CID])
REFERENCES [dbo].[STORE] ([CID])
GO
ALTER TABLE [dbo].[ITEM_ORDER] CHECK CONSTRAINT [FK_ITEM_ORDER_REF_STORE]
GO
ALTER TABLE [dbo].[ITEM_ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_ORDER_REF_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[SUPPLIER] ([ID])
GO
ALTER TABLE [dbo].[ITEM_ORDER] CHECK CONSTRAINT [FK_ITEM_ORDER_REF_SUPPLIER]
GO
ALTER TABLE [dbo].[ITEM_ORDER_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_ORDER_LINE_REF_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([ID])
GO
ALTER TABLE [dbo].[ITEM_ORDER_LINE] CHECK CONSTRAINT [FK_ITEM_ORDER_LINE_REF_ITEM]
GO
ALTER TABLE [dbo].[ITEM_ORDER_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_ORDER_LINE_REF_ITEM_ORDER] FOREIGN KEY([ITEM_ORDER_ID])
REFERENCES [dbo].[ITEM_ORDER] ([ID])
GO
ALTER TABLE [dbo].[ITEM_ORDER_LINE] CHECK CONSTRAINT [FK_ITEM_ORDER_LINE_REF_ITEM_ORDER]
GO
ALTER TABLE [dbo].[ITEM_PICKING]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PICKING_REF_ITEM_ORDER] FOREIGN KEY([ITEM_ORDER_ID])
REFERENCES [dbo].[ITEM_ORDER] ([ID])
GO
ALTER TABLE [dbo].[ITEM_PICKING] CHECK CONSTRAINT [FK_ITEM_PICKING_REF_ITEM_ORDER]
GO
ALTER TABLE [dbo].[ITEM_PICKING]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PICKING_REF_STORE] FOREIGN KEY([STORE_CID])
REFERENCES [dbo].[STORE] ([CID])
GO
ALTER TABLE [dbo].[ITEM_PICKING] CHECK CONSTRAINT [FK_ITEM_PICKING_REF_STORE]
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PICKING_LINE_REF_ITEM_ORDER_LINE] FOREIGN KEY([ITEM_ORDER_LINE_ID])
REFERENCES [dbo].[ITEM_ORDER_LINE] ([ID])
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE] CHECK CONSTRAINT [FK_ITEM_PICKING_LINE_REF_ITEM_ORDER_LINE]
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PICKING_LINE_REF_ITEM_PICKING] FOREIGN KEY([ITEM_PICKING_ID])
REFERENCES [dbo].[ITEM_PICKING] ([ID])
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE] CHECK CONSTRAINT [FK_ITEM_PICKING_LINE_REF_ITEM_PICKING]
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PICKING_LINE_REF_ITEM_PKG] FOREIGN KEY([ITEM_PKG_ID])
REFERENCES [dbo].[ITEM_PKG] ([ID])
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE] CHECK CONSTRAINT [FK_ITEM_PICKING_LINE_REF_ITEM_PKG]
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PICKING_LINE_REF_STORE_POS] FOREIGN KEY([STORE_POS_CID])
REFERENCES [dbo].[STORE_POS] ([CID])
GO
ALTER TABLE [dbo].[ITEM_PICKING_LINE] CHECK CONSTRAINT [FK_ITEM_PICKING_LINE_REF_STORE_POS]
GO
ALTER TABLE [dbo].[ITEM_PKG]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PKG_REF_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([ID])
GO
ALTER TABLE [dbo].[ITEM_PKG] CHECK CONSTRAINT [FK_ITEM_PKG_REF_ITEM]
GO
ALTER TABLE [dbo].[ITEM_PKG]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PKG_REF_PACKAGE_TYPE] FOREIGN KEY([PACKAGE_TYPE_CID])
REFERENCES [dbo].[PACKAGE_TYPE] ([CID])
GO
ALTER TABLE [dbo].[ITEM_PKG] CHECK CONSTRAINT [FK_ITEM_PKG_REF_PACKAGE_TYPE]
GO
ALTER TABLE [dbo].[ITEM_SPEC]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_SPEC_REF_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([ID])
GO
ALTER TABLE [dbo].[ITEM_SPEC] CHECK CONSTRAINT [FK_ITEM_SPEC_REF_ITEM]
GO
ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_REF_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO
ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_PAYMENT_REF_CUSTOMER]
GO
ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_REF_ITEM_ORDER] FOREIGN KEY([ITEM_ORDER_ID])
REFERENCES [dbo].[ITEM_ORDER] ([ID])
GO
ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_PAYMENT_REF_ITEM_ORDER]
GO
ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_REF_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[SUPPLIER] ([ID])
GO
ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_PAYMENT_REF_SUPPLIER]
GO
ALTER TABLE [dbo].[PAYMENT_LINE]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_LINE_REF_BANK_ACCOUNT] FOREIGN KEY([BANK_ACCOUNT_ID])
REFERENCES [dbo].[BANK_ACCOUNT] ([ID])
GO
ALTER TABLE [dbo].[PAYMENT_LINE] CHECK CONSTRAINT [FK_PAYMENT_LINE_REF_BANK_ACCOUNT]
GO
ALTER TABLE [dbo].[PAYMENT_LINE]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_LINE_REF_PAYMENT] FOREIGN KEY([PAYMENT_ID])
REFERENCES [dbo].[PAYMENT] ([ID])
GO
ALTER TABLE [dbo].[PAYMENT_LINE] CHECK CONSTRAINT [FK_PAYMENT_LINE_REF_PAYMENT]
GO
ALTER TABLE [dbo].[PAYMENT_LINE]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_LINE_REF_PAYMENT_TYPE] FOREIGN KEY([PAYMENT_TYPE_CID])
REFERENCES [dbo].[PAYMENT_TYPE] ([CID])
GO
ALTER TABLE [dbo].[PAYMENT_LINE] CHECK CONSTRAINT [FK_PAYMENT_LINE_REF_PAYMENT_TYPE]
GO
ALTER TABLE [dbo].[PRODUCTION]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTION_REF_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTION] CHECK CONSTRAINT [FK_PRODUCTION_REF_ITEM]
GO
ALTER TABLE [dbo].[PRODUCTION]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTION_REF_PRODUCTION_PHASE] FOREIGN KEY([PRODUCTION_PHASE_CID])
REFERENCES [dbo].[PRODUCTION_PHASE] ([CID])
GO
ALTER TABLE [dbo].[PRODUCTION] CHECK CONSTRAINT [FK_PRODUCTION_REF_PRODUCTION_PHASE]
GO
ALTER TABLE [dbo].[PRODUCTION_PART]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTION_PART_REF_ITEM] FOREIGN KEY([ITEM_ID])
REFERENCES [dbo].[ITEM] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTION_PART] CHECK CONSTRAINT [FK_PRODUCTION_PART_REF_ITEM]
GO
ALTER TABLE [dbo].[PRODUCTION_PART]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTION_PART_REF_PRODUCTION] FOREIGN KEY([PRODUCTION_ID])
REFERENCES [dbo].[PRODUCTION] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTION_PART] CHECK CONSTRAINT [FK_PRODUCTION_PART_REF_PRODUCTION]
GO
ALTER TABLE [dbo].[PRODUCTION_PART]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTION_PART_REF_PRODUCTION_MACHINE] FOREIGN KEY([PRODUCTION_MACHINE_CID])
REFERENCES [dbo].[PRODUCTION_MACHINE] ([CID])
GO
ALTER TABLE [dbo].[PRODUCTION_PART] CHECK CONSTRAINT [FK_PRODUCTION_PART_REF_PRODUCTION_MACHINE]
GO
ALTER TABLE [dbo].[REGION]  WITH CHECK ADD  CONSTRAINT [FK_REGIN_REF_COUNTRY] FOREIGN KEY([COUNTRY_CID])
REFERENCES [dbo].[COUNTRY] ([CID])
GO
ALTER TABLE [dbo].[REGION] CHECK CONSTRAINT [FK_REGIN_REF_COUNTRY]
GO
ALTER TABLE [dbo].[STORE_POS]  WITH CHECK ADD  CONSTRAINT [FK_STORE_POS_STORE] FOREIGN KEY([STORE_CID])
REFERENCES [dbo].[STORE] ([CID])
GO
ALTER TABLE [dbo].[STORE_POS] CHECK CONSTRAINT [FK_STORE_POS_STORE]
GO
ALTER TABLE [dbo].[SUPPLIER]  WITH CHECK ADD  CONSTRAINT [FK_SUPPLIER_REF_SUPPLIER_CATEGORY] FOREIGN KEY([SUPPLIER_CATEGORY_CID])
REFERENCES [dbo].[SUPPLIER_CATEGORY] ([CID])
GO
ALTER TABLE [dbo].[SUPPLIER] CHECK CONSTRAINT [FK_SUPPLIER_REF_SUPPLIER_CATEGORY]
GO
ALTER TABLE [dbo].[SUPPLIER_CATEGORY]  WITH CHECK ADD  CONSTRAINT [SK_SUPPLIER_CATEGORY_01] FOREIGN KEY([PARENT_CATEGORY_CID])
REFERENCES [dbo].[SUPPLIER_CATEGORY] ([CID])
GO
ALTER TABLE [dbo].[SUPPLIER_CATEGORY] CHECK CONSTRAINT [SK_SUPPLIER_CATEGORY_01]
GO
ALTER TABLE [dbo].[SUPPLIER_PLACE]  WITH CHECK ADD  CONSTRAINT [FK_SUPPLIER_PLACE_REF_CITY] FOREIGN KEY([CITY_ID])
REFERENCES [dbo].[CITY] ([ID])
GO
ALTER TABLE [dbo].[SUPPLIER_PLACE] CHECK CONSTRAINT [FK_SUPPLIER_PLACE_REF_CITY]
GO
ALTER TABLE [dbo].[SUPPLIER_PLACE]  WITH CHECK ADD  CONSTRAINT [FK_SUPPLIER_PLACE_REF_SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[SUPPLIER] ([ID])
GO
ALTER TABLE [dbo].[SUPPLIER_PLACE] CHECK CONSTRAINT [FK_SUPPLIER_PLACE_REF_SUPPLIER]
GO
USE [master]
GO
ALTER DATABASE [Item Specifications] SET  READ_WRITE 
GO
